core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from django.conf import settings
from django.conf.urls.static import static


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('privacy/', views.privacy, name='privacy'),
    path('logout/', views.logout_view, name='logout'),
    path('terms/', views.terms, name='terms'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name='login'), 
    path('logout/', views.logout_view, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('delete_account/', views.delete_account, name='delete_account'),  
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path('', views.items , name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

nestfixer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/' , include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'), name='reset_password'),
    
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_sent.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_form.html'), name='password_reset_confirm'),
    
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_done.html'), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import PasswordChangeForm

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Customize the widget attributes for password fields
        self.fields['old_password'].widget.attrs['class'] = 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
        self.fields['new_password1'].widget.attrs['class'] = 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
        self.fields['new_password2'].widget.attrs['class'] = 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Customize form fields if needed
        self.fields['username'].widget.attrs['class'] = 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
        self.fields['username'].widget.attrs['placeholder'] = 'Enter your username'

        self.fields['email'].widget.attrs['class'] = 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter your email'

        
        # Check for the correct field names for password change
        if 'password' in self.fields:
            self.fields['password'].widget.attrs['class'] = 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
            self.fields['password'].widget.attrs['placeholder'] = 'Enter Old Password'

        if 'new_password1' in self.fields:
            self.fields['new_password1'].widget.attrs['class'] = 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
            self.fields['new_password1'].widget.attrs['placeholder'] = 'Enter New Password'
        if 'new_password2' in self.fields:
            self.fields['new_password2'].widget.attrs['class'] = 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
            self.fields['new_password1'].widget.attrs['placeholder'] = 'Confirm New Password'





class LoginForm(AuthenticationForm):
    
    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter Username',
        'class': 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
    }))
    
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
    }))
     


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields=('username' , 'email' , 'password1' , 'password2')

    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter Username',
        'class': 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
    }))

    email=forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Enter Email',
        'class': 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
    }))

    password1=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
    }))

    password2=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'class': 'w-full py-4 px-6 rounded-xl bg-white border border-gray-400 text-gray-900 text-sm rounded-lg  focus:border-blue-500'
    }))

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match.")

        return cleaned_data

core/views.py
from django.shortcuts import redirect, render
from item.models import category, Item
from .forms import SignupForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render, redirect
from .forms import EditProfileForm
from django.contrib import messages
from .forms import EditProfileForm, CustomPasswordChangeForm
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Avg

from django.db.models import Avg, Min

def index(request):
    items = Item.objects.filter(is_available=True).order_by('-id')[:4]
    highest_rated_items = Item.objects.annotate(avg_rating=Avg('review__rating')).exclude(avg_rating__isnull=True).order_by('-avg_rating')[:4]
    cheapest_items = Item.objects.filter(is_available=True).order_by('price')[:4]
    categories = category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
        'highest_rated_items': highest_rated_items,
        'cheapest_items': cheapest_items,
    })



def contact(request):
    return render(request, 'core/contact.html')

def faq(request):
    return render(request ,'core/faq.html')

def privacy(request):
    return render(request ,'core/privacy.html')

def terms(request):
    return render(request ,'core/terms.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, f"Welcome, {user.username}!")
                return redirect('core:index')
            else:
                messages.error(request, "Invalid username or password.")
                return render(request, 'core/login.html', {'form': form})

    else:
        form = AuthenticationForm()

    return render(request, 'core/login.html', {'form': form})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            password1 = form.cleaned_data.get('password1')
            password2 = form.cleaned_data.get('password2')

            if password1 != password2:
                messages.error(request, "Passwords do not match.")
                return render(request, 'core/signup.html', {'form': form})

            form.save()
            messages.success(request, "Account created successfully. You can now log in.")
            return redirect('/login')

    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {'form': form})
    
@login_required
def edit_profile(request):
    if request.method == 'POST':
        if 'change_user_info' in request.POST:
            user_form = EditProfileForm(request.POST, instance=request.user)
            if user_form.is_valid():
                user_form.save()
                messages.success(request, 'Your profile information was successfully updated.')
                return redirect('core:index')
            else:
                messages.error(request, 'Please correct the errors below.')
        elif 'change_password' in request.POST:
            password_form = CustomPasswordChangeForm(user=request.user, data=request.POST)
            if password_form.is_valid():
                password_form.save()
                update_session_auth_hash(request, password_form.user)
                messages.success(request, 'Your password was successfully updated.')
                return redirect('core:index')
            else:
                messages.error(request, 'Please correct the errors below.')
    else:
        user_form = EditProfileForm(instance=request.user)
        password_form = CustomPasswordChangeForm(user=request.user)

    return render(request, 'core/edit_profile.html', {
        'user_form': user_form,
        'password_form': password_form,
    })



@login_required
def delete_account(request):
    if request.method == 'POST':
        request.user.delete()
        logout(request)
        messages.success(request, 'Your account has been successfully deleted.')
        return redirect('core:index')

    user_form = EditProfileForm(instance=request.user)
    password_form = CustomPasswordChangeForm(user=request.user)

    return render(request, 'core/edit_profile.html', {
        'user_form': user_form,
        'password_form': password_form,
    })

def logout_view(request):
    logout(request)
    return redirect ("core:login")

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script src="https://cdn.tailwindcss.com"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></script>

    <title>{% block title %} {% endblock %} | NestFixer</title>
  </head>

  <body class="flex flex-col min-h-screen">
    
    {% include 'core/navbar.html'%}

    <div class="mt-14  pt-6">{% block content %} {% endblock %}</div>

    {% include 'core/footer.html'%}

  </body>
</html>

core/templates/core/getstarted.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="container mx-auto my-14 md:px-6">
        <section class="background-radial-gradient mb-32">
          <style>
            .background-radial-gradient {
              background-color: hsl(218, 41%, 15%);
              background-image: radial-gradient(
                  650px circle at 0% 0%,
                  hsl(218, 41%, 35%) 15%,
                  hsl(218, 41%, 30%) 35%,
                  hsl(218, 41%, 20%) 75%,
                  hsl(218, 41%, 19%) 80%,
                  transparent 100%
                ),
                radial-gradient(
                  1250px circle at 100% 100%,
                  hsl(218, 41%, 45%) 15%,
                  hsl(218, 41%, 30%) 35%,
                  hsl(218, 41%, 20%) 75%,
                  hsl(218, 41%, 19%) 80%,
                  transparent 100%
                );
            }
          </style>
      
          <div class="px-6 py-12 text-center md:px-12 lg:text-left">
            <div class="container mx-auto xl:px-32">
              <div class="flex grid items-center gap-12 lg:grid-cols-2">
                <div class="mt-12 lg:mt-0">
                  <h1
                    class="mb-6 text-5xl font-bold tracking-tight text-white md:text-6xl xl:text-7xl"
                  >
                    The best offer <br /><span class="text-gray-300"
                      >for your Services</span
                    >
                  </h1>
                  <a
                    class="mb-2 inline-block rounded bg-neutral-50 px-12 pt-4 pb-3.5 text-sm font-medium uppercase leading-normal text-neutral-800 transition duration-150 ease-in-out focus:outline-none focus:ring-0 active:bg-neutral-200 active:shadow-[0_8px_9px_-4px_rgba(203,203,203,0.3),0_4px_18px_0_rgba(203,203,203,0.2)] shadow-[0_4px_9px_-4px_rgba(251,251,251,0.3)] hover:shadow-[0_8px_9px_-4px_rgba(251,251,251,0.1),0_4px_18px_0_rgba(251,251,251,0.05)] focus:shadow-[0_8px_9px_-4px_rgba(251,251,251,0.1),0_4px_18px_0_rgba(251,251,251,0.05)] active:shadow-[0_8px_9px_-4px_rgba(251,251,251,0.1),0_4px_18px_0_rgba(251,251,251,0.05)] md:mr-2 md:mb-0"
                    data-te-ripple-init
                    data-te-ripple-color="light"
                    role="button"
                    href="{% url 'core:signup' %}"
                    >Get started</a
                  >
      
                </div>
                <div class="mb-12 lg:mb-0">
                  <img
                    src="media\static\images\mathiko2.png"
                    class="w-full rounded-lg shadow-lg"
                    alt=""
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
Welcome
{% endblock %}
{% block content %}  

<!-- slider -->
{% include 'core/slider.html'%}


<!-- Categoreis -->
<div class="mt-3 px-6 py-3 bg-gray-50 rounded-xl">
  <div>
  <h2 class="mb-1 ml-3 text-3xl text-center text-yellow-500 font-bold">
    Explore through our
    <u class="text-sky-950 ">
      Popular Categories</u>
  </h2>
  </div>
  <div>
    
    <div class="flex items-center justify-center w-full h-full py-24 sm:py-8 px-4">
      <div class="w-full relative flex items-center justify-center">
          <button aria-label="slide backward" class="absolute z-30 left-0 ml-10 focus:outline-none focus:bg-gray-400 focus:ring-2 focus:ring-offset-2 focus:ring-gray-400 cursor-pointer" id="prev">
              <svg class="dark:text-gray-900" width="16" height="28"viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M7 1L1 7L7 13" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
          </button>
          <div class="w-full h-full mx-auto overflow-x-hidden overflow-y-hidden">
              <div id="slider" class="h-full flex lg:gap-8 md:gap-6 gap-14 items-center justify-start transition ease-out duration-700">
                  <div class="flex flex-shrink-0 relative w-full sm:w-auto">
                      <a href="{% url 'item:items' %}?query={{ query }}&Category=1" >
                        <img src="media\static\images\electricain.png" class="object-cover object-center w-full transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg" />
                      </a>
                  </div>
                  <div class="flex flex-shrink-0 relative w-full sm:w-auto">
                    <a href="{% url 'item:items' %}?query={{ query }}&Category=2" >
                      <img src="media\static\images\plumber.png" class="object-cover object-center w-full rounded-lg transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg" />
                    </a>
                  </div>
                  <div class="flex flex-shrink-0 relative w-full sm:w-auto">
                    <a href="{% url 'item:items' %}?query={{ query }}&Category=3" >
                      <img src="media\static\images\painter.png" class="object-cover object-center w-full transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg" />
                    </a>
                  </div>
                  <div class="flex flex-shrink-0 relative w-full sm:w-auto">
                    <a href="{% url 'item:items' %}?query={{ query }}&Category=4" >
                      <img src="media\static\images\furniture.png" class="object-cover object-center w-full transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg" />
                    </a>
                  </div>
                  <div class="flex flex-shrink-0 relative w-full sm:w-auto">
                    <a href="{% url 'item:items' %}?query={{ query }}&Category=5" >
                      <img src="media\static\images\conditioniong.png" class="object-cover object-center w-full transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg" />
                    </a>
                  </div>
                  <div class="flex flex-shrink-0 relative w-full sm:w-auto">
                    <a href="{% url 'item:items' %}?query={{ query }}&Category=6" >
                      <img src="media\static\images\carpenter.png" class="object-cover object-center w-full transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg" />
                    </a>
                  </div>
                  <div class="flex flex-shrink-0 relative w-full sm:w-auto">
                    <a href="{% url 'item:items' %}?query={{ query }}&Category=7" >
                      <img src="media\static\images\repairmen.png" class="object-cover object-center w-full transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg" />
                    </a>
                  </div>
                  <div class="flex flex-shrink-0 relative w-full sm:w-auto">
                    <a href="{% url 'item:items' %}?query={{ query }}&Category=8" >
                      <img src="media\static\images\mechanic.png" class="object-cover object-center w-full transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg" />
                    </a>
                  </div>
              </div>
          </div>
          <button aria-label="slide forward" class="absolute z-30 right-0 mr-10 focus:outline-none focus:bg-gray-400 focus:ring-2 focus:ring-offset-2 focus:ring-gray-400" id="next">
              <svg class="dark:text-gray-900" width="16" height="28" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1 1L7 7L1 13" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
          </button>
      </div>
  </div>

  <script>
    let defaultTransform = 0;
function goNext() {
    defaultTransform = defaultTransform - 398;
    var slider = document.getElementById("slider");
    if (Math.abs(defaultTransform) >= slider.scrollWidth / 1.7) defaultTransform = 0;
    slider.style.transform = "translateX(" + defaultTransform + "px)";
}
next.addEventListener("click", goNext);
function goPrev() {
    var slider = document.getElementById("slider");
    if (Math.abs(defaultTransform) === 0) defaultTransform = 0;
    else defaultTransform = defaultTransform + 398;
    slider.style.transform = "translateX(" + defaultTransform + "px)";
}
prev.addEventListener("click", goPrev);

  </script>



  </div>
</div>


<!-- Newest Services -->
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-4 text-2xl text-center font-bold text-black dark:text-black border-b-2 border-gray-300 dark:border-gray-300 pb-2">
    Newest Services
  </h2>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
    {% for item in items %}
    <a href="{% url 'item:detail' item.id %}">
      <div class="mx-auto mt-6 w-full md:w-80 transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg">
        <img src="{{ item.image.url }}" class="w-full h-48 object-cover">
        <div class="px-6 py-4">
            <h2 class="font-bold text-xl mb-1">{{ item.name }}</h2>
            <p class="text-gray-700">{{ item.Category }}</p>
            <div class="showcase-rating mb-1">
                {% if item.average_rating %}
                    {% for i in "12345" %}
                        {% if i|add:"0" <= item.average_rating %}
                            <i class="fa fa-star checked" id="check-star" style="color: gold;"></i>
                        {% else %}
                            <i class="fa fa-star" id="check-star" style="color: rgb(228, 227, 227);"></i>
                        {% endif %}
                    {% endfor %}
                    <span class="text-gray-400 text-xs">{{ item.average_rating|floatformat:2 }}/5</span>
                {% else %}
                  <span class="text-gray-400 text-xs">&nbsp;</span>
                {% endif %}
            </div>
            <p class="text-amber-600 font-semibold text-2xl">Rs. {{ item.price }} per day</p>
            
            
        </div>
    </div>
    </a>
    {% endfor %}
  </div>
</div>

<!-- Highest Rated -->
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-4 text-2xl text-center font-bold text-black dark:text-black border-b-2 border-gray-300 dark:border-gray-300 pb-2">
    Highest Rated Services
  </h2>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
    {% for item in highest_rated_items %}
      <a href="{% url 'item:detail' item.id %}">
        <div class="mx-auto mt-6 w-full md:w-80 transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg">
          <img src="{{ item.image.url }}" class="w-full h-48 object-cover">
          <div class="px-6 py-4">
              <h2 class="font-bold text-xl mb-1">{{ item.name }}</h2>
              <p class="text-gray-700">{{ item.Category }}</p>
              <div class="showcase-rating mb-1">
                  {% if item.average_rating %}
                      {% for i in "12345" %}
                          {% if i|add:"0" <= item.average_rating %}
                              <i class="fa fa-star checked" id="check-star" style="color: gold;"></i>
                          {% else %}
                              <i class="fa fa-star" id="check-star" style="color: rgb(228, 227, 227);"></i>
                          {% endif %}
                      {% endfor %}
                      <span class="text-gray-400 text-xs">{{ item.average_rating|floatformat:2 }}/5</span>
                  {% else %}
                      <span class="text-gray-400 text-xs">&nbsp;</span>
                  {% endif %}
              </div>
              <p class="text-amber-600 font-semibold text-2xl">Rs. {{ item.price }} per day</p>
              
              
          </div>
      </div>
      </a>
    {% endfor %}
  </div>
</div>


<!-- offers -->
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-4 text-2xl text-center font-bold text-black dark:text-black border-b-2 border-gray-300 dark:border-gray-300 pb-2">
    Offers
  </h2>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
    {% for item in cheapest_items %}
    <a href="{% url 'item:detail' item.id %}">
      <div class="mx-auto mt-6 w-full md:w-80 transform overflow-hidden rounded-lg bg-gray-100 dark:bg-white shadow-md duration-300 hover:scale-105 hover:shadow-lg">
        <img src="{{ item.image.url }}" class="w-full h-48 object-cover">
        <div class="px-6 py-4">
            <h2 class="font-bold text-xl mb-1">{{ item.name }}</h2>
            <p class="text-gray-700">{{ item.Category }}</p>
            <div class="showcase-rating mb-1">
                {% if item.average_rating %}
                    {% for i in "12345" %}
                        {% if i|add:"0" <= item.average_rating %}
                            <i class="fa fa-star checked" id="check-star" style="color: gold;"></i>
                        {% else %}
                            <i class="fa fa-star" id="check-star" style="color: rgb(228, 227, 227);"></i>
                        {% endif %}
                    {% endfor %}
                    <span class="text-gray-400 text-xs">{{ item.average_rating|floatformat:2 }}/5</span>
                {% else %}
                    <span class="text-gray-400 text-xs">&nbsp;</span>
                {% endif %}
            </div>
            <p class="text-amber-600 font-semibold text-2xl">Rs. {{ item.price }} per day</p>
            
            
        </div>
    </div>
    </a>
    {% endfor %}
  </div>
</div>


<!-- Mid-Section FAQ -->
{% include 'core/midsectionfaq.html'%}

<!-- Testimonial -->
{% include 'core/testimonial.html'%}

  <!-- Features -->
{% include 'core/features.html'%}


  
{% endblock %}

core/templates/core/password_reset.html
{% extends 'core/base.html' %}

{% block title %} Reset Password {% endblock %}

{% block content %}

<section class="min-h-screen flex items-center justify-center bg-gradient-to-r from-yellow-100 to-indigo-100">
    <div class="w-full bg-white rounded-lg shadow-md max-w-md p-6 space-y-6 md:space-y-6 ">
        <h1 class="text-xl font-bold leading-tight text-gray-900 md:text-3xl">
            Forgot your password?
        </h1>
        <form class="space-y-6 md:space-y-6" method="post">
            {% csrf_token %} 
            <div class="mb-4">
                <label for="{{ form.email.id_for_label }}" class="block mb-2 text-m font-medium text-gray-900">
                    Don't worry! Just type in your email and we will send you a code to reset your password!
                </label>
                
                <div class="email">
                    <input type="email" name="email" autocomplete="email" required="" id="id_email" class="bg-white text-black border border-gray-300 p-2 rounded-md" value="{{ form.id_email.email }}" placeholder="Enter your email">
                </div>
                
            </div>
            <div class="mb-4">
                <label class="flex items-center">
                    <input type="checkbox" class="text-blue-500 focus:ring-0 border-gray-300">
                    <span class="ml-2 text-gray-700 text-sm">I agree to the <a href="{%url 'core:terms'%}" class="underline">Terms and Conditions</a></span>
                </label>
            </div>
            <button type="submit" class="w-full bg-blue-500 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 text-white font-medium rounded-lg text-sm px-5 py-2.5">
                Reset Password
            </button>

            
        </form>
    </div>
</section>

{% endblock %}