conversation/urls.py
from django.urls import path
from . import views
 
app_name = 'conversation'

urlpatterns =[
    path('',views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation,name = 'new')
]

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from django.conf import settings
from django.conf.urls.static import static


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('privacy/', views.privacy, name='privacy'),
    path('logout/', views.logout_view, name='logout'),
    path('terms/', views.terms, name='terms'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name='login'), 
    path('logout/', views.logout_view, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('delete_account/', views.delete_account, name='delete_account'),  
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path('', views.items , name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

nestfixer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/' , include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='core/password_reset.html'), name='reset_password'),
    
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_sent.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_form.html'), name='password_reset_confirm'),
    
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_done.html'), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

class category(models.Model):
    name=models.CharField(max_length=255)
    
    class Meta: 
        # category lai order ma rakhna 
        ordering = ('name',)

        # Spelling Milauna
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        # Cateogy lai afno naam dina lai
        return self.name

class Item(models.Model):
    Category = models.ForeignKey(category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_available = models.BooleanField(default=False)
    is_negotiable = models.BooleanField(default=False)
    location = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    facebook = models.CharField(max_length=255, blank=True, null=True, help_text='Enter Facebook link')
    instagram = models.CharField(max_length=255, blank=True, null=True, help_text='Enter Instagram link')
    qr = models.ImageField(upload_to='item_images', blank=True, null=True, help_text='Upload QR code image')
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def average_rating(self):
        avg_rating = review.objects.filter(item=self).aggregate(avg_rating=Avg('rating'))
        return avg_rating['avg_rating'] if avg_rating['avg_rating'] else 0

    def __str__(self):
        return self.name

class  review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    review_desp = models.CharField(max_length=100)
    rating = models.IntegerField()

item/forms.py
from django import forms
from .models import Item

# Define common classes for styling
INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'
CHECKBOX_CLASSES = 'border'
SELECT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('Category', 'name', 'location', 'description', 'price', 'image', 'phone_number', 'email', 'is_available', 'is_negotiable', 'facebook', 'instagram', 'qr')

        widgets = {
            'Category': forms.Select(attrs={'class': SELECT_CLASSES}),
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter Name'}),
            'location': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter Location'}),
            'description': forms.Textarea(attrs={'class': f'{INPUT_CLASSES} resize-none', 'placeholder': 'Enter post description'}),  
            'price': forms.NumberInput(attrs={'class': f'{INPUT_CLASSES} text-green-500', 'placeholder': 'Enter Price per Day'}),
            'image': forms.ClearableFileInput(attrs={'class': f'{INPUT_CLASSES} bg-blue-500 text-white'}),
            'phone_number': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter phonenumber'}),
            'email': forms.EmailInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter email'}),
            'is_available': forms.CheckboxInput(attrs={'class': CHECKBOX_CLASSES}),
            'is_negotiable': forms.CheckboxInput(attrs={'class': CHECKBOX_CLASSES}),
            'facebook': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter Facebook link'}),
            'instagram': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter Instagram link'}),
            'qr': forms.ClearableFileInput(attrs={'class': f'{INPUT_CLASSES} bg-blue-500 text-white'}),
        }

    def clean_image(self):
        image = self.cleaned_data.get('image')

        if not image:
            raise forms.ValidationError("Please select an image.")
        
        return image
    
    def clean_qr(self):
        qr = self.cleaned_data.get('qr')

        if not qr:
            raise forms.ValidationError("Please select a QR image.")
        
        return qr
    
    


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'location', 'description', 'price', 'image', 'phone_number', 'email', 'is_available', 'is_negotiable', 'facebook', 'instagram', 'qr')

        widgets = {
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter item name'}),
            'location': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter location'}),
            'description': forms.Textarea(attrs={'class': f'{INPUT_CLASSES} resize-none', 'placeholder': 'Enter post description'}),  
            'price': forms.NumberInput(attrs={'class': f'{INPUT_CLASSES} text-green-500', 'placeholder': 'Enter Price per Day'}),
            'image': forms.ClearableFileInput(attrs={'class': f'{INPUT_CLASSES} bg-blue-500 text-white'}),
            'phone_number': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter phone number'}),
            'email': forms.EmailInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter email'}),
            'is_available': forms.CheckboxInput(attrs={'class': CHECKBOX_CLASSES}),
            'is_negotiable': forms.CheckboxInput(attrs={'class': CHECKBOX_CLASSES}),
            'facebook': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter Facebook link'}),
            'instagram': forms.TextInput(attrs={'class': INPUT_CLASSES, 'placeholder': 'Enter Instagram link'}),
            'qr': forms.ClearableFileInput(attrs={'class': f'{INPUT_CLASSES} bg-blue-500 text-white'}),
        }

    def clean_image(self):
        image = self.cleaned_data.get('image')

        if not image:
            raise forms.ValidationError("Please select an image.")
        
        return image
    
    def clean_qr(self):
        qr = self.cleaned_data.get('qr')

        if not qr:
            raise forms.ValidationError("Please select a QR image.")
        
        return qr
    
    
    

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Item, category, review
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm
from django.db.models import Avg
from django.db import IntegrityError
from django.contrib import messages




from django.db.models import Avg

def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('Category', 0)
    sort_by_price = request.GET.get('sort', '')
    sort_by_rating = request.GET.get('sort', '')
    is_negotiable = request.GET.get(' is_negotiable', '')
    min_price = request.GET.get('min_price', '')
    max_price = request.GET.get('max_price', '')


    categories = category.objects.all()
    items = Item.objects.filter(is_available=True)

    if category_id:
        items = items.filter(Category__id=category_id)
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    if sort_by_price == 'highest':
        items = items.order_by('-price')
    elif sort_by_price == 'lowest':
        items = items.order_by('price')

    if sort_by_rating == 'highest_rated':
        items = items.annotate(avg_rating=Avg('review__rating')).exclude(avg_rating__isnull=True).order_by('-avg_rating')
    elif sort_by_rating == 'lowest_rated':
        items = items.annotate(avg_rating=Avg('review__rating')).exclude(avg_rating__isnull=True).order_by('avg_rating')

    if request.method == 'GET':
        is_negotiable = request.GET.get('is_negotiable', '')
        min_price = request.GET.get('min_price', '')
        max_price = request.GET.get('max_price', '')

        # Filter items based on is_negotiable
        if is_negotiable != '':
            items = items.filter(is_negotiable=is_negotiable)

        # Filter items based on price range
        if min_price:
            items = items.filter(price__gte=min_price)
        if max_price:
            items = items.filter(price__lte=max_price)
    # ... (existing code)

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
        'sort_by_price': sort_by_price,
        'sort_by_rating': sort_by_rating,
        'is_negotiable': is_negotiable,
        'min_price': min_price,
        'max_price': max_price,
    })



def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    reviews = review.objects.filter(item=item)
    avg_rating = reviews.aggregate(Avg('rating'))['rating__avg']


    related_items = Item.objects.filter(Category=item.Category, is_available=True).exclude(pk=pk)[0:3]

    if request.method == 'POST':
        star_rating = request.POST.get('rating')
        item_review = request.POST.get('item_review')

        try:
            review.objects.create(user=request.user, item=item, rating=star_rating, review_desp=item_review)
        except IntegrityError:
            messages.error(request, "Please fill all the fields")
        else:
            # Redirect to the same detail page after successful review submission so that the user should not resubmit data on reload
            return redirect('item:detail', pk=pk)

    return render(request, 'item/detail.html', {
        'item': item,
        'reviews': reviews,
        'related_items': related_items,
        'avg_rating': avg_rating,         
        
    })



@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', pk=item.id)

    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item'
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect('dashboard:index')



@login_required
def edit(request,pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES , instance=item)

        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)

    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item'
    })

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New Post</title>
    <link href="https://cdn.tailwindcss.com" rel="stylesheet">
</head>
<body class="bg-gray-100">
    <div class="mx-6">
        <section class="container mx-auto py-8 ">
        <div class="bg-gradient-to-r from-yellow-100 to-indigo-100 shadow-md rounded px-8 pt-6 pb-8 mb-4 ">
            <h2 class="mb-4 text-2xl font-bold text-gray-900">Add a new post</h2>
            <h2 class="mb-4 text-l font-bold text-gray-900 dark:text-black">You can edit your details later..</h2>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div class="mb-4">
                        <label for="id_Category" class="block mb-2 text-sm font-medium text-gray-700">Category:</label>
                        {{ form.Category }}
                    </div>
                    <div class="mb-4">
                        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-700">Name:</label>
                        {{ form.name }}
                    </div>
                    <div class="mb-4 col-span-2">
                        <label for="id_description" class="block mb-2 text-sm font-medium text-gray-700 ">Description:</label>
                        {{ form.description }}
                    </div>
                    <div class="mb-4">
                        <label for="id_location" class="block mb-2 text-sm font-medium text-gray-700">Location:</label>
                        {{ form.location }}
                    </div>
                
                    <div class="mb-4">
                        <label for="id_price" class="block mb-2 text-sm font-medium text-gray-700">Price:</label>
                        {{ form.price }}
                    </div>
                    <div class="mb-4">
                        <label for="id_image" class="block mb-2 text-sm font-medium text-gray-700">Image:</label>
                        {{ form.image }}
                    </div>
                    <div class="mb-4">
                        <label for="id_phone_number" class="block mb-2 text-sm font-medium text-gray-700">Phone Number:</label>
                        {{ form.phone_number }}
                    </div>
                    <div class="mb-4">
                        <label for="id_email" class="block mb-2 text-sm font-medium text-gray-700">Email:</label>
                        {{ form.email }}
                    </div>

                    <div class="mb-4">
                        <label for="id_facebook" class="block mb-2 text-sm font-medium text-gray-700">Facebook:</label>
                        {{ form.facebook }}
                    </div>
                    <div class="mb-4">
                        <label for="id_instagram" class="block mb-2 text-sm font-medium text-gray-700">Instagram:</label>
                        {{ form.instagram }}
                    </div>
                    <div class="mb-4">
                        <label for="id_qr" class="block mb-2 text-sm font-medium text-gray-700">QR Code:</label>
                        {{ form.qr }}
                    </div>

                   
                    <div class="mb-4">
                        <label for="id_is_available" class="block mb-2 text-sm font-medium text-gray-700">Is Available:</label>{{ form.is_available }}
                        <label for="id_is_negotiable" class="block mb-2 text-sm font-medium text-gray-700">Is Negotiable:</label>{{ form.is_negotiable }}
                    </div>
                    
                    
                    
                </div>
                <label for="des" class=" block mb-2 text-m font-medium text-gray-900 dark:black">⚠️ Please fill all the boxes with valid credentials</label>
                <div class="flex items-center">
                    <input id="link-checkbox" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                    <label for="link-checkbox" class="ms-2 text-sm font-medium text-gray-black dark:text-black">I agree with the <a href="{%url 'core:terms'%}" class="text-blue-600 dark:text-blue-500 hover:underline">terms and conditions</a>.</label>
                </div>
                {% if form.errors or form.non_field_errors %}
                <div class="mt-2 p-4 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
                <button class="mt-6 py-3 px-6 text-sm bg-blue-500 hover:bg-blue-700 text-gray-50 font-bold rounded-full" type="submit">+ Add Post</button>
            </form>
        </div>
        </section>
    </div>
</body>
</html>

    


{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %} Browse {% endblock %}

{% block content %}
    <div class="mx-5">
        <form class="mb-4 flex items-center" method="get" action="{% url 'item:items' %}">
            <div class="relative w-full">
                <input name="query" class="w-full my-2 py-2 bg-gray-200 border border-gray-300 rounded-md" type="text" value="{{ query }}" placeholder="   Search from here">
            </div>
            <button type="submit" class="p-2.5 ms-2 text-sm font-medium text-white bg-blue-900 rounded-lg border border-indigo-900 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300">
                <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                </svg>
                <span class="sr-only">Search</span>
            </button>
        </form>

        <div>
            <div class="flex items-center justify-end mb-2">
                <p class="text-black">Sort by: </p>
                <form action="{% url 'item:items' %}" method="get" class="ml-2">
                    <select name="sort" class="font-medium text-black bg-transparent dark:text-gray-500 focus:outline-none" onchange="this.form.submit()">
                        <option value="" {% if not sort_by_price and not sort_by_rating %} selected {% endif %}>Newest</option>
                        <option value="lowest" {% if sort_by_price == 'lowest' %} selected {% endif %}>Price: Low to High</option>
                        <option value="highest" {% if sort_by_price == 'highest' %} selected {% endif %}>Price: High to Low</option>
                        <option value="lowest_rated" {% if sort_by_rating == 'lowest_rated' %} selected {% endif %}>Lowest Rated</option>
                        <option value="highest_rated" {% if sort_by_rating == 'highest_rated' %} selected {% endif %}>Highest Rated</option>
                    </select>
                </form>
            </div>
        </div>

        <div class="pb-5 pl-10 mt-6 grid grid-cols-4 gap-4 px-1 flex overflow-y-auto">
            <div class="pb-6 p-4 flex flex-col justify-start rounded-lg max-5-sm shadow-lg">
                <h1 class="mx-6 font-bold rounded-4xl text-xl text-sky-950 mb-4">SEARCH BY FILTERS</h1>
                <hr class="my-1">
                <h2 class="text-blue-900 font-medium text-xl mt-2">Categories</h2>
                <ul>
                    {% for category in categories %}
                        <li class="py-2 items-center rounded-xl {% if category.id == category_id %} bg-gray-100 {% endif %}">
                            <a class="text-blue-800 font-semibold hover:underline" href="{% url 'item:items' %}?query={{ query }}&Category={{ category.id }}">{{ category.name }} ({{ category.items.count }})</a>
                        </li>
                    {% endfor %}
                </ul>

                <hr class="my-6">

                <!-- Add is_negotiable filter -->
                <form class="" method="get" action="{% url 'item:items' %}">
                    <label for="is_negotiable" class="block text-blue-900 font-medium text-xl">Negotiable</label>
                    <select name="is_negotiable" class="mt-1 mb-2 p-2 w-full border rounded-lg">
                        <option value="" {% if is_negotiable is None %} selected {% endif %}>All</option>
                        <option value="1" {% if is_negotiable == '1' %} selected {% endif %}>Negotiable</option>
                        <option value="0" {% if is_negotiable == '0' %} selected {% endif %}>Not Negotiable</option>
                    </select>

                    <!-- Add price range filter -->
                    <label for="min_price" class="block text-blue-900 font-medium text-xl">Min Price</label>
                    <input type="number" name="min_price" class="mt-1 mb-2 p-2 w-full border rounded-lg" value="{{ min_price }}">

                    <label for="max_price" class="block text-blue-900 font-medium text-xl">Max Price</label>
                    <input type="number" name="max_price" class="mt-1 mb-2 p-2 w-full border rounded-lg" value="{{ max_price }}">
                    
                    <div class="flex justify-center">
                        <button type="submit" class="p-3 mt-3 w-64 text-sm font-medium text-white bg-blue-900 rounded-lg border border-indigo-900 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300">
                            Apply Filters
                        </button>
                    </div>
                </form>

                <hr class="mt-5">
                <div class="flex justify-center">
                    <ul>
                        <li class="px-6 mt-5">
                            <a href="{% url 'item:items'%}" class="my-2 p-3 w-64 text-sm font-medium text-white bg-blue-900 rounded-lg border border-indigo-900 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300">Reset Filters</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-span-3 ml-4">
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-4 overflow-y-auto">
                    {% for item in items %}
                        <div class="mb-4">
                            <a href="{% url 'item:detail' item.id %}">
                                <div class="max-w-xs rounded overflow-hidden shadow-md hover:text-blue-900 hover:shadow-lg">
                                    <img src="{{ item.image.url }}" class="w-full h-48 object-cover">
                                    <div class="px-6 py-4">
                                        <h2 class="font-bold text-xl mb-1">{{ item.name }}</h2>
                                        <p class="text-gray-700">{{ item.Category }}</p>
                                        <div class="showcase-rating mb-1">
                                            {% if item.average_rating %}
                                                {% for i in "12345" %}
                                                    {% if i|add:"0" <= item.average_rating %}
                                                        <i class="fa fa-star checked" id="check-star" style="color: gold;"></i>
                                                    {% else %}
                                                        <i class="fa fa-star" id="check-star" style="color: rgb(228, 227, 227);"></i>
                                                    {% endif %}
                                                {% endfor %}
                                                <span class="text-gray-400 text-xs">{{ item.average_rating|floatformat:2 }}/5</span>
                                            {% else %}
                                                <span class="text-gray-400 text-xs">&nbsp;</span>
                                            {% endif %}
                                        </div>
                                        <p class="text-amber-600 font-semibold text-2xl">Rs. {{ item.price }} per day</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}